import type { Metadata } from 'next';
import { Caveat } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

import NavHeader from '@/components/molecules/NavHeader';

const zodiak = localFont({
    src: '../public/fonts/Zodiak-Variable.woff2',
    variable: '--font-zodiak',
    display: 'swap',
});

const caveat = Caveat({
    variable: '--font-caveat',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${zodiak.variable} ${caveat.variable} antialiased `}>
                <NavHeader />
                <main className="min-h-screen pb-10 md:mx-10 md:border-l md:border-r">
                    {children}
                </main>
                <section className="border-t border-b p-10">
                    <p className="w-50">
                        I am Hashim - a front-end developer. Thanks for checking out my site!
                    </p>
                </section>
            </body>
        </html>
    );
}
