import type { Metadata } from 'next';
import { Geist, Geist_Mono, Caveat } from 'next/font/google';
import './globals.css';

import NavHeader from '@/components/molecules/NavHeader';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

const caveat = Caveat({
    variable: '--font-caveat',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${caveat.variable} antialiased`}
            >
                <NavHeader />
                <main className="min-h-screen mx-10 md:border-l md:border-r">{children}</main>
                <section className="border-t border-b p-10">
                    <p className="w-50">
                        I am Hashim - a front-end developer. Thanks for checking out my site!
                    </p>
                </section>
            </body>
        </html>
    );
}
